# Site settings
title: Xu Sun
tagline: 'Chinese student living in Guangzhou.'
email: pamixsun@gmail.com
description: 'Personal site of Xu Sun, an Chinese student living in Guangzhou.'
baseurl: ""
url: "http://pamixsun.github.io"

author:
  name:           'Xu Sun'
  url:            http://weibo.com/u/1847756827

# Build settings
markdown: kramdown
permalink: pretty

paginate:         5

gems:
  - jekyll-sitemap

