# Site settings
title: PamixSun
tagline: 'Personal site of Xu Sun.'
email: pamixsun@gmail.com
description: 'Personal site of Xu Sun, an AI practitioner working in Guangzhou.'
baseurl: ""
url: "http://pamixsun.github.io"

author:
  name:           'Xu Sun'
  url:            http://pamixsun.github.io

# Build settings
markdown: kramdown
permalink: pretty

paginate:         5

gems:
  - jekyll-sitemap

