# Site settings
title: Always With Me
tagline: 'Personal site of Xu Sun.'
email: pamixsun@gmail.com
description: 'Personal site of Xu Sun, a Chinese student studing in Guangzhou.'
baseurl: ""
url: "http://pamixsun.github.io"

author:
  name:           'Xu Sun'
  url:            http://weibo.com/u/1847756827

# Build settings
markdown: kramdown
permalink: pretty

paginate:         5

gems:
  - jekyll-sitemap

